name: shipanther
description: Manage your shipment business like a panther
publish_to: "none"
version: 0.0.9+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^7.0.0-nullsafety.5
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  smart_select: ^4.3.2
  intl: ^0.17.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  enum_to_string: ^2.0.0-nullsafety.1
  trober_sdk: 0.0.36
  date_time_picker: ^2.0.0
  package_info_plus: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  percent_indicator: ^2.1.9+1
  flex_color_scheme: ^2.0.0
  image_picker: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  mockito: ^5.0.1
  flutter_launcher_icons: ^0.9.0
  intl_translation: ^0.17.10+1
  pedantic: ^1.11.0

dependency_overrides:
  intl: ^0.17.0
  analyzer: ^1.1.0
  test_api: ^0.3.0
  xml: ^5.0.2
  petitparser: ^4.0.2
  args: ^2.0.0
  http_parser: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/shipanther_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shipanther_logo.png"
  adaptive_icon_background: "#0896c9"
  adaptive_icon_foreground: assets/images/shipanther_logo.png
