name: shipanther
description: Manage your shipment business like a panther
publish_to: "none"
version: 0.0.9+9

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0-nullsafety.2
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.21.0-nullsafety.0
  firebase_core: ^0.8.0-nullsafety.1
  firebase_crashlytics: ^0.5.0-1.0.nullsafety.2
  firebase_messaging: ^9.0.0-1.0.nullsafety.0
  firebase_storage: ^7.0.0
  smart_select: ^4.3.2
  intl: ^0.17.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  enum_to_string: ^1.0.14
  trober_sdk: 0.0.36
  date_time_picker: ^1.1.1
  package_info: ^0.5.0-nullsafety
  material_design_icons_flutter: ^4.0.5855
  percent_indicator: ^2.1.9+1
  flex_color_scheme: ^2.0.0-nullsafety.1
  image_picker: ^0.7.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  mockito: ^5.0.0-nullsafety.7
  flutter_launcher_icons: ^0.8.1
  intl_translation: ^0.17.10+1
  pedantic: ^1.10.0

dependency_overrides:
  intl: ^0.17.0
  firebase_core: ^0.8.0-nullsafety.1
  firebase_core_platform_interface: ^4.0.0-nullsafety.0
  firebase_core_web: ^0.3.0-nullsafety.0
  http: ^0.13.0-nullsafety.0
  http_parser: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/shipanther_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shipanther_logo.png"
  adaptive_icon_background: "#0896c9"
  adaptive_icon_foreground: assets/images/shipanther_logo.png
