name: shipanther
description: Manage your shipment business like a panther
publish_to: "none"
version: 0.0.13+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^7.0.0
  firebase_analytics: ^8.0.2
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.2
  firebase_messaging: ^9.1.3
  firebase_storage: ^8.0.5
  smart_select: ^4.3.2
  intl: ^0.17.0
  flutter_typeahead: ^3.1.1
  enum_to_string: ^2.0.1
  trober_sdk: 0.0.48
  date_time_picker: ^2.0.0
  package_info_plus: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  percent_indicator: ^3.3.0-nullsafety.1
  flex_color_scheme: ^2.1.1
  image_picker: ^0.7.4
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  mockito: ^5.0.6
  flutter_launcher_icons: ^0.9.0
  pedantic: ^1.11.0
  intl_utils: ^2.1.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/shipanther_logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shipanther_logo.png"
  adaptive_icon_background: "#0896c9"
  adaptive_icon_foreground: assets/images/shipanther_logo.png

flutter_intl:
  enabled: true
  class_name: ShipantherLocalizations
  main_locale: en
  arb_dir: i18n
  output_dir: lib/l10n/locales